name: MultiInventory
author: NgLoader
version: 1.0.0

main: de.ngloader.multiinventory.MultiInventory

depend: [ImprexStorage]
loadbefore: [ImprexStorage]

commands:
  multiinventory:
    aliases: [multiinv, minv, minventory]